name: Test Suite

on: [push, pull_request]

jobs:
  nui__and_game_scripts:
    name: Tests for NUI and Game scripts
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Install dependencis
        run: pnpm i --frozen-lockfile
      - name: Check build status
        run: pnpm build
        env:
          CI: true

  lint:
    name: Lint Lua scripts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/game 
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: GoatG33k/fivem-lua-lint-action@v1
